### ISSUE TITLE
DigitalOcean

### ISSUE THREAD

**Issue by cmcky** [danleech/simple-icons#238]
<img width="327" alt="screen shot 2015-10-22 at 7 35 20 pm" src="https://cloud.githubusercontent.com/assets/5117005/10681252/49ea7466-78f5-11e5-9e9a-6712ee4b44d2.png">
`DigitalOcean`
`#2481B7`

Github does not support .svg, so we are just going to link to a public google drive folder for now - https://drive.google.com/open?id=0B9EgKynIClM7LXBLQWY3X2xFeVU

Let us know if this is sufficient until we figure out a build process and can submit PRs.

**Comment by danleech** [comment]
@cmcky I’ve added a rough build process to the README.

DigitalOcean was a particularly interesting one, since the vector assets they provide were faulty (there were portions of the left-hand curve of the cloud that had intersecting strokes). I’ve fixed it and added it. The colour used on the site’s logo SVG is #3190E7.
